const assert=require('node:assert/strict');
const backup=require('../.test-build/backups.js');
const {newDraft}=require('../.test-build/drafts.js');
const draft=newDraft('one');
const raw=JSON.stringify({kind:'quote-builder',version:1,drafts:[draft]});
assert.deepEqual(backup.parseBackup(raw),[draft]);
for(const raw of ['x'.repeat(1000001),'null','{}',JSON.stringify({kind:'quote-builder',version:2,drafts:[]})])assert.throws(()=>backup.parseBackup(raw));
assert.throws(()=>backup.parseBackup('😀'.repeat(250001)));
assert.throws(()=>backup.parseBackup(JSON.stringify({kind:'quote-builder',version:1,drafts:[draft,draft]})));
assert.throws(()=>backup.parseBackup(JSON.stringify({kind:'quote-builder',version:1,drafts:[{...draft,items:[{id:1,description:'Bad',quantity:1,cents:-1}]}]})));
assert.equal(backup.mergeBackup([draft],[draft])[1].id,'import-1');
assert.throws(()=>backup.mergeBackup(Array(20).fill(draft),[draft]));
assert.equal(backup.mergeBackup([draft],[draft])[1].name,'Untitled quote (import 1)');
assert.equal(backup.mergeBackup([draft],[draft,draft])[2].name,'Untitled quote (import 2)');
assert.deepEqual(backup.parseBackup(backup.serializeBackup([draft])),[draft]);
assert.throws(()=>backup.serializeBackup(Array(21).fill(draft)));
const twenty=Array.from({length:20},(_,i)=>({...draft,id:String(i)}));
assert.equal(backup.mergeBackup(twenty,[]).length,20);
assert.throws(()=>backup.mergeBackup(twenty,[draft]));
assert.equal(twenty.length,20);
